<?php

namespace AppBundle\Repository;

/**
 * CatgorieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatgorieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
