<?php

namespace AppBundle\Repository;

/**
 * ListeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
